//// Gleam handler-stub generator for AsyncAPI.
////
//// Emits one handler-stub function per operation, grouped by channel. `receive`
//// operations become `handle_*` stubs (messages arriving from the client);
//// `send` operations become `emit_*` helpers (messages the app pushes out).
//// Payload types are referenced by name — generate them with nori's Gleam type
//// generator from the same schemas.

import gleam/list
import gleam/string
import nori/codegen/ir as nori_ir
import nori/codegen/naming
import nori_asyncapi/ir.{type AsyncCodegenIR, type ChannelIR, type OperationIR}

/// Generate a `.gleam` handler-stub module from the IR.
///
/// `types_module` is the import path of the companion types module produced by
/// `generate_gleam_types` (e.g. `"generated/types"`); named payload types are
/// referenced through its `types` alias.
pub fn generate(spec: AsyncCodegenIR, types_module: String) -> String {
  let imports =
    "import gleam/dict.{type Dict}\n"
    <> "import gleam/dynamic.{type Dynamic}\n"
    <> "import gleam/option.{type Option}\n"
    <> "import "
    <> types_module
    <> " as types\n"

  let header =
    "//// Generated by nori_asyncapi. Handler stubs — fill in the bodies.\n"
    <> "//// Source: "
    <> spec.title
    <> " v"
    <> spec.version
    <> "\n\n"
    <> imports
    <> "\n"

  let channels =
    spec.channels
    |> list.map(channel_to_gleam)
    |> string.join("\n\n")

  header <> channels <> "\n"
}

fn channel_to_gleam(ch: ChannelIR) -> String {
  let banner =
    "// ---------------------------------------------------------------------------\n"
    <> "// channel: "
    <> ch.address
    <> "\n"
    <> "// ---------------------------------------------------------------------------\n"
  let ops =
    ch.operations
    |> list.map(fn(op) { operation_to_gleam(ch, op) })
    |> string.join("\n\n")
  banner <> ops
}

fn operation_to_gleam(ch: ChannelIR, op: OperationIR) -> String {
  let fn_name = naming.to_snake_case(op.operation_id)
  let payload = payload_type(op)
  case op.action {
    ir.Receive ->
      "/// Handle `"
      <> op.operation_id
      <> "` arriving on `"
      <> ch.address
      <> "`.\n"
      <> "pub fn handle_"
      <> fn_name
      <> "(msg: "
      <> payload
      <> ") -> Nil {\n"
      <> "  todo\n"
      <> "}"
    ir.Send ->
      "/// Emit `"
      <> op.operation_id
      <> "` on `"
      <> ch.address
      <> "`.\n"
      <> "pub fn emit_"
      <> fn_name
      <> "(msg: "
      <> payload
      <> ") -> Nil {\n"
      <> "  todo\n"
      <> "}"
  }
}

fn payload_type(op: OperationIR) -> String {
  case list.first(op.messages) {
    Ok(m) -> type_ref_to_gleam(m.payload)
    Error(_) -> "Dynamic"
  }
}

fn type_ref_to_gleam(ref: nori_ir.TypeRef) -> String {
  case ref {
    nori_ir.Named(name) -> "types." <> name
    nori_ir.Primitive(p) -> primitive_to_gleam(p)
    nori_ir.Array(item) -> "List(" <> type_ref_to_gleam(item) <> ")"
    nori_ir.Dict(k, v) ->
      "Dict(" <> type_ref_to_gleam(k) <> ", " <> type_ref_to_gleam(v) <> ")"
    nori_ir.Nullable(inner) -> "Option(" <> type_ref_to_gleam(inner) <> ")"
    nori_ir.Optional(inner) -> "Option(" <> type_ref_to_gleam(inner) <> ")"
    nori_ir.Literal(_) -> "String"
    nori_ir.Unknown -> "Dynamic"
  }
}

fn primitive_to_gleam(p: nori_ir.PrimitiveType) -> String {
  case p {
    nori_ir.PString -> "String"
    nori_ir.PInt -> "Int"
    nori_ir.PFloat -> "Float"
    nori_ir.PBool -> "Bool"
    nori_ir.PDateTime -> "String"
    nori_ir.PDate -> "String"
    nori_ir.PBinary -> "BitArray"
    nori_ir.PUnit -> "Nil"
  }
}
