//// Gleam server dispatcher generator.
////
//// Emits a transport-neutral runtime that turns incoming JSON frames into
//// typed handler calls and outgoing messages into JSON frames. It is not
//// coupled to any server library — feed `dispatch` each received text frame
//// (from Mist, or anything) and send the string that `send_*` returns.
////
//// Wire protocol: a `{ "type": "<MessageName>", "payload": <payload> }`
//// envelope. `type` names the AsyncAPI message; `payload` is its schema.
////
//// Direction is from the server's point of view: `receive` operations (client
//// → server) become handler callbacks; `send` operations (server → client)
//// become `send_*` encoders.

import gleam/list
import gleam/string
import nori/codegen/ir as nori_ir
import nori/codegen/naming
import nori_asyncapi/ir.{type AsyncCodegenIR, type MessageIR}

/// Generate the server dispatcher module. `types_module` is the import path of
/// the companion types module (e.g. `"generated/types"`).
pub fn generate(spec: AsyncCodegenIR, types_module: String) -> String {
  let incoming = messages_for_action(spec, ir.Receive)
  let outgoing = messages_for_action(spec, ir.Send)

  // only pull in Dynamic when a payload actually falls back to it
  let needs_dynamic =
    list.append(incoming, outgoing)
    |> list.any(fn(m) { payload_type(m.payload) == "Dynamic" })
  let dynamic_import = case needs_dynamic {
    True -> "import gleam/dynamic.{type Dynamic}\n"
    False -> ""
  }

  let header =
    "//// Generated by nori_asyncapi. Server dispatcher — transport-neutral.\n"
    <> "//// Source: "
    <> spec.title
    <> " v"
    <> spec.version
    <> "\n\n"
    <> dynamic_import
    <> "import gleam/dynamic/decode\n"
    <> "import gleam/json\n"
    <> "import "
    <> types_module
    <> " as types\n\n"

  header
  <> error_type()
  <> "\n\n"
  <> handlers_section(incoming)
  <> encoders_section(outgoing)
}

fn error_type() -> String {
  "/// Why a frame could not be dispatched.\n"
  <> "pub type DispatchError {\n"
  <> "  /// The frame was not a JSON envelope with a string `type`.\n"
  <> "  BadEnvelope\n"
  <> "  /// No handler exists for this message `type`.\n"
  <> "  UnknownMessage(kind: String)\n"
  <> "  /// The payload did not match the message schema.\n"
  <> "  DecodeFailed(kind: String)\n"
  <> "}"
}

// ---------------------------------------------------------------------------
// Incoming: Handlers record + dispatch
// ---------------------------------------------------------------------------

fn handlers_section(incoming: List(MessageIR)) -> String {
  case incoming {
    [] -> "// No `receive` operations — nothing to dispatch.\n"
    _ -> {
      let fields =
        incoming
        |> list.map(fn(m) {
          "    "
          <> handler_field(m)
          <> ": fn("
          <> payload_type(m.payload)
          <> ") -> Nil,"
        })
        |> string.join("\n")

      let handlers_type =
        "/// Your message handlers, one per client\u{2192}server message.\n"
        <> "pub type Handlers {\n"
        <> "  Handlers(\n"
        <> fields
        <> "\n  )\n"
        <> "}"

      let arms =
        incoming
        |> list.map(dispatch_arm)
        |> string.join("\n")

      let dispatch =
        "/// Decode a received frame and route it to the matching handler.\n"
        <> "pub fn dispatch(\n"
        <> "  handlers: Handlers,\n"
        <> "  frame: String,\n"
        <> ") -> Result(Nil, DispatchError) {\n"
        <> "  case json.parse(frame, decode.at([\"type\"], decode.string)) {\n"
        <> "    Error(_) -> Error(BadEnvelope)\n"
        <> "    Ok(kind) -> route(handlers, kind, frame)\n"
        <> "  }\n"
        <> "}\n\n"
        <> "fn route(\n"
        <> "  handlers: Handlers,\n"
        <> "  kind: String,\n"
        <> "  frame: String,\n"
        <> ") -> Result(Nil, DispatchError) {\n"
        <> "  case kind {\n"
        <> arms
        <> "\n    _ -> Error(UnknownMessage(kind))\n"
        <> "  }\n"
        <> "}"

      handlers_type <> "\n\n" <> dispatch <> "\n\n"
    }
  }
}

fn dispatch_arm(m: MessageIR) -> String {
  let #(_, decoder) = payload_type_and_decoder(m.payload)
  "    \""
  <> m.name
  <> "\" ->\n"
  <> "      case json.parse(frame, decode.at([\"payload\"], "
  <> decoder
  <> ")) {\n"
  <> "        Ok(payload) -> {\n"
  <> "          handlers."
  <> handler_field(m)
  <> "(payload)\n"
  <> "          Ok(Nil)\n"
  <> "        }\n"
  <> "        Error(_) -> Error(DecodeFailed(kind))\n"
  <> "      }"
}

// ---------------------------------------------------------------------------
// Outgoing: send_* encoders
// ---------------------------------------------------------------------------

fn encoders_section(outgoing: List(MessageIR)) -> String {
  case outgoing {
    [] -> "// No `send` operations — nothing to encode.\n"
    _ ->
      outgoing
      |> list.map(encoder_fn)
      |> string.join("\n\n")
      |> string.append("\n")
  }
}

fn encoder_fn(m: MessageIR) -> String {
  let payload = payload_type(m.payload)
  "/// Encode a `"
  <> m.name
  <> "` message into a frame to send to the client.\n"
  <> "pub fn send_"
  <> naming.to_snake_case(m.name)
  <> "(msg: "
  <> payload
  <> ") -> String {\n"
  <> "  json.object([\n"
  <> "    #(\"type\", json.string(\""
  <> m.name
  <> "\")),\n"
  <> "    #(\"payload\", "
  <> payload_encoder(m.payload)
  <> "),\n"
  <> "  ])\n"
  <> "  |> json.to_string\n"
  <> "}"
}

// ---------------------------------------------------------------------------
// Payload type / decoder / encoder mapping
// ---------------------------------------------------------------------------

fn handler_field(m: MessageIR) -> String {
  "on_" <> naming.to_snake_case(m.name)
}

fn payload_type(ref: nori_ir.TypeRef) -> String {
  case ref {
    nori_ir.Named(name) -> "types." <> name
    nori_ir.Primitive(p) -> primitive_type(p)
    nori_ir.Array(item) -> "List(" <> payload_type(item) <> ")"
    _ -> "Dynamic"
  }
}

fn payload_type_and_decoder(ref: nori_ir.TypeRef) -> #(String, String) {
  #(payload_type(ref), payload_decoder(ref))
}

fn payload_decoder(ref: nori_ir.TypeRef) -> String {
  case ref {
    nori_ir.Named(name) ->
      "types." <> naming.to_snake_case(name) <> "_decoder()"
    nori_ir.Primitive(p) -> primitive_decoder(p)
    nori_ir.Array(item) -> "decode.list(" <> payload_decoder(item) <> ")"
    _ -> "decode.dynamic"
  }
}

fn payload_encoder(ref: nori_ir.TypeRef) -> String {
  case ref {
    nori_ir.Named(name) ->
      "types.encode_" <> naming.to_snake_case(name) <> "(msg)"
    nori_ir.Primitive(p) -> primitive_encoder(p)
    _ -> "json.null()"
  }
}

fn primitive_type(p: nori_ir.PrimitiveType) -> String {
  case p {
    nori_ir.PString -> "String"
    nori_ir.PInt -> "Int"
    nori_ir.PFloat -> "Float"
    nori_ir.PBool -> "Bool"
    _ -> "String"
  }
}

fn primitive_decoder(p: nori_ir.PrimitiveType) -> String {
  case p {
    nori_ir.PString -> "decode.string"
    nori_ir.PInt -> "decode.int"
    nori_ir.PFloat -> "decode.float"
    nori_ir.PBool -> "decode.bool"
    _ -> "decode.string"
  }
}

fn primitive_encoder(p: nori_ir.PrimitiveType) -> String {
  case p {
    nori_ir.PString -> "json.string(msg)"
    nori_ir.PInt -> "json.int(msg)"
    nori_ir.PFloat -> "json.float(msg)"
    nori_ir.PBool -> "json.bool(msg)"
    _ -> "json.string(msg)"
  }
}

fn messages_for_action(
  spec: AsyncCodegenIR,
  action: ir.Action,
) -> List(MessageIR) {
  spec.channels
  |> list.flat_map(fn(ch) { ch.operations })
  |> list.filter(fn(op) { op.action == action })
  |> list.flat_map(fn(op) { op.messages })
  |> dedupe_by_name
}

fn dedupe_by_name(msgs: List(MessageIR)) -> List(MessageIR) {
  msgs
  |> list.fold(#([], []), fn(acc, m) {
    let #(seen, out) = acc
    case list.contains(seen, m.name) {
      True -> acc
      False -> #([m.name, ..seen], [m, ..out])
    }
  })
  |> fn(acc) { list.reverse(acc.1) }
}
