//// Gleam handler-stub generator for AsyncAPI.
////
//// Emits one handler-stub function per `receive` operation, grouped by channel.
//// `receive` operations (messages arriving from the client) become `handle_*`
//// stubs. `send` operations are the server's outgoing messages — encode those
//// with the `send_*` functions in the generated server module, not here — so
//// they contribute nothing to this file. Payload types are referenced by name;
//// generate them with nori's Gleam type generator from the same schemas.

import gleam/list
import gleam/string
import nori/codegen/ir as nori_ir
import nori/codegen/naming
import nori_asyncapi/ir.{type AsyncCodegenIR, type ChannelIR, type OperationIR}

/// Generate a `.gleam` handler-stub module from the IR.
///
/// `types_module` is the import path of the companion types module produced by
/// `generate_gleam_types` (e.g. `"generated/types"`); named payload types are
/// referenced through its `types` alias.
pub fn generate(spec: AsyncCodegenIR, types_module: String) -> String {
  let channels =
    spec.channels
    |> list.filter_map(channel_to_gleam)
    |> string.join("\n\n")

  // Only import what the generated stubs actually reference, so a spec with no
  // `receive` operations (or only primitive payloads) does not emit unused
  // imports that `gleam build` would warn on. With no handlers at all, emit no
  // imports — not even `types`, which nothing would reference.
  let imports = case channels {
    "" -> ""
    _ ->
      import_if(contains(channels, "Dict("), "gleam/dict.{type Dict}")
      <> import_if(
        contains(channels, "Dynamic"),
        "gleam/dynamic.{type Dynamic}",
      )
      <> import_if(contains(channels, "Option("), "gleam/option.{type Option}")
      <> "import "
      <> types_module
      <> " as types\n"
  }

  let header =
    "//// Generated by nori_asyncapi. Handler stubs — fill in the bodies.\n"
    <> "//// Source: "
    <> spec.title
    <> " v"
    <> spec.version
    <> "\n\n"
    <> imports
    <> "\n"

  let body = case channels {
    "" -> "// No `receive` operations — nothing to handle.\n"
    _ -> channels <> "\n"
  }

  header <> body
}

/// Whether this spec produces any handler stubs. False for a send-only spec,
/// in which case `handlers.gleam` would be an empty module and should not be
/// written at all (an empty module warns on `gleam build`).
pub fn has_handlers(spec: AsyncCodegenIR) -> Bool {
  spec.channels
  |> list.any(fn(ch) {
    list.any(ch.operations, fn(op) { op.action == ir.Receive })
  })
}

fn contains(haystack: String, needle: String) -> Bool {
  string.contains(does: haystack, contain: needle)
}

fn import_if(needed: Bool, module: String) -> String {
  case needed {
    True -> "import " <> module <> "\n"
    False -> ""
  }
}

/// Returns `Error(Nil)` for channels with no `receive` operations so they are
/// dropped entirely — a send-only channel has nothing to handle here.
fn channel_to_gleam(ch: ChannelIR) -> Result(String, Nil) {
  let handlers =
    ch.operations
    |> list.filter(fn(op) { op.action == ir.Receive })
    |> list.map(fn(op) { operation_to_gleam(ch, op) })

  case handlers {
    [] -> Error(Nil)
    _ -> {
      let banner =
        "// ---------------------------------------------------------------------------\n"
        <> "// channel: "
        <> ch.address
        <> "\n"
        <> "// ---------------------------------------------------------------------------\n"
      Ok(banner <> string.join(handlers, "\n\n"))
    }
  }
}

fn operation_to_gleam(ch: ChannelIR, op: OperationIR) -> String {
  let fn_name = naming.to_snake_case(op.operation_id)
  let payload = payload_type(op)
  "/// Handle `"
  <> op.operation_id
  <> "` arriving on `"
  <> ch.address
  <> "`.\n"
  <> "pub fn handle_"
  <> fn_name
  <> "(msg: "
  <> payload
  <> ") -> Nil {\n"
  <> "  todo\n"
  <> "}"
}

fn payload_type(op: OperationIR) -> String {
  case list.first(op.messages) {
    Ok(m) -> type_ref_to_gleam(m.payload)
    Error(_) -> "Dynamic"
  }
}

fn type_ref_to_gleam(ref: nori_ir.TypeRef) -> String {
  case ref {
    nori_ir.Named(name) -> "types." <> name
    nori_ir.Primitive(p) -> primitive_to_gleam(p)
    nori_ir.Array(item) -> "List(" <> type_ref_to_gleam(item) <> ")"
    nori_ir.Dict(k, v) ->
      "Dict(" <> type_ref_to_gleam(k) <> ", " <> type_ref_to_gleam(v) <> ")"
    nori_ir.Nullable(inner) -> "Option(" <> type_ref_to_gleam(inner) <> ")"
    nori_ir.Optional(inner) -> "Option(" <> type_ref_to_gleam(inner) <> ")"
    nori_ir.Literal(_) -> "String"
    nori_ir.Unknown -> "Dynamic"
  }
}

fn primitive_to_gleam(p: nori_ir.PrimitiveType) -> String {
  case p {
    nori_ir.PString -> "String"
    nori_ir.PInt -> "Int"
    nori_ir.PFloat -> "Float"
    nori_ir.PBool -> "Bool"
    nori_ir.PDateTime -> "String"
    nori_ir.PDate -> "String"
    nori_ir.PBinary -> "BitArray"
    nori_ir.PUnit -> "Nil"
  }
}
