//// TypeScript generator for AsyncAPI.
////
//// Emits payload interfaces, a small transport runtime (WebSocket + SSE behind
//// one `Transport` interface), and one typed class per channel.
////
//// Direction is inverted to the client's point of view: AsyncAPI `action` is
//// written from the application (server) side, so a server `send` becomes a
//// client `on*` subscription and a server `receive` becomes a client `send*`
//// publish. Channel address variables become a typed `connect` parameter.

import gleam/list
import gleam/option.{type Option, None, Some}
import gleam/string
import nori/codegen/ir as nori_ir
import nori_asyncapi/ir.{
  type AsyncCodegenIR, type ChannelIR, type MessageIR, type OperationIR,
}

/// Generate the neutral TypeScript client: payload interfaces, the transport
/// runtime, and one typed class per channel. No framework dependency.
pub fn generate(spec: AsyncCodegenIR) -> String {
  let types = spec.types |> list.map(type_def_to_ts) |> string.join("\n\n")
  let transport = transport_runtime()
  let default = default_transport(spec)
  let channels =
    spec.channels
    |> list.map(fn(ch) { channel_to_ts(ch, default) })
    |> string.join("\n\n")

  [banner(spec), types, transport, channels]
  |> list.filter(fn(s) { s != "" })
  |> string.join("\n\n")
}

/// Generate the neutral store layer: one `create*Store` observable per
/// subscribe message, shaped for `useSyncExternalStore` (or any framework's
/// subscribe/snapshot store). Imports the channel classes and payload types
/// from `client_module` (e.g. `"./client"`). Framework-agnostic — imports no
/// UI library.
pub fn generate_stores(spec: AsyncCodegenIR, client_module: String) -> String {
  let stores = spec.channels |> list.flat_map(channel_stores)
  case stores {
    [] -> banner(spec) <> "\n// No subscribe messages — nothing to store.\n"
    _ -> {
      let imports = store_imports(spec, client_module)
      [banner(spec), imports, string.join(stores, "\n\n")]
      |> string.join("\n\n")
    }
  }
}

fn banner(spec: AsyncCodegenIR) -> String {
  "// Generated by nori_asyncapi. Do not edit by hand.\n"
  <> "// Source: "
  <> spec.title
  <> " v"
  <> spec.version
  <> "\n"
}

// ---------------------------------------------------------------------------
// Gateway transport
//
// One WebSocket multiplexing every channel via a `{ "type", "payload" }`
// envelope — the wire format the generated Gleam server dispatcher speaks. Use
// this instead of the per-channel `generate` when the server is a single /ws
// gateway. Direction is still inverted to the client's view: a server `send`
// message becomes an `on*` subscription, a server `receive` becomes a `send*`.
// ---------------------------------------------------------------------------

type GatewayMethod {
  GwSubscribe(method: String, msg_type: String, payload: String)
  GwPublish(method: String, msg_type: String, payload: String)
}

/// Generate a single gateway client (payload types + one multiplexing client).
pub fn generate_gateway(spec: AsyncCodegenIR) -> String {
  let types = spec.types |> list.map(type_def_to_ts) |> string.join("\n\n")
  let methods =
    spec.channels
    |> list.flat_map(gateway_methods)
    |> dedupe_gateway
    |> list.map(render_gateway_method)
    |> string.join("\n\n")

  [banner(spec), types, gateway_runtime(methods)]
  |> list.filter(fn(s) { s != "" })
  |> string.join("\n\n")
}

fn gateway_methods(ch: ChannelIR) -> List(GatewayMethod) {
  ch.operations
  |> list.flat_map(fn(op) {
    list.map(op.messages, fn(msg) {
      let method_suffix = to_pascal(msg.name)
      let payload = type_ref_to_ts(msg.payload)
      case op.action {
        ir.Send -> GwSubscribe("on" <> method_suffix, msg.name, payload)
        ir.Receive -> GwPublish("send" <> method_suffix, msg.name, payload)
      }
    })
  })
}

fn dedupe_gateway(methods: List(GatewayMethod)) -> List(GatewayMethod) {
  methods
  |> list.fold(#([], []), fn(acc, m) {
    let #(seen, out) = acc
    let name = case m {
      GwSubscribe(method:, ..) -> method
      GwPublish(method:, ..) -> method
    }
    case list.contains(seen, name) {
      True -> acc
      False -> #([name, ..seen], [m, ..out])
    }
  })
  |> fn(acc) { list.reverse(acc.1) }
}

fn render_gateway_method(m: GatewayMethod) -> String {
  case m {
    GwSubscribe(method:, msg_type:, payload:) ->
      "  /** Subscribe to `"
      <> msg_type
      <> "` messages. Returns an unsubscribe function. */\n"
      <> "  "
      <> method
      <> "(handler: (msg: "
      <> payload
      <> ") => void): () => void {\n"
      <> "    return this.subscribe(\""
      <> msg_type
      <> "\", handler as (p: unknown) => void);\n"
      <> "  }"
    GwPublish(method:, msg_type:, payload:) ->
      "  /** Publish a `"
      <> msg_type
      <> "` message. */\n"
      <> "  "
      <> method
      <> "(msg: "
      <> payload
      <> "): void {\n"
      <> "    this.publish(\""
      <> msg_type
      <> "\", msg);\n"
      <> "  }"
  }
}

fn gateway_runtime(methods: String) -> String {
  "export class GatewayClient {
  private ws: WebSocket;
  private handlers = new Map<string, Set<(p: unknown) => void>>();

  constructor(url: string) {
    this.ws = new WebSocket(url);
    this.ws.addEventListener(\"message\", (e) => {
      let env: { type?: string; payload?: unknown };
      try {
        env = JSON.parse(e.data);
      } catch {
        console.warn(\"[asyncapi] dropping unparseable frame:\", e.data);
        return;
      }
      if (!env.type) return;
      this.handlers.get(env.type)?.forEach((h) => h(env.payload));
    });
  }

  /** Connect to a gateway URL (add any auth/query params to `url`). */
  static connect(url: string): GatewayClient {
    return new GatewayClient(url);
  }

  private subscribe(type: string, handler: (p: unknown) => void): () => void {
    let set = this.handlers.get(type);
    if (!set) {
      set = new Set();
      this.handlers.set(type, set);
    }
    set.add(handler);
    return () => {
      set.delete(handler);
    };
  }

  private publish(type: string, payload: unknown): void {
    this.ws.send(JSON.stringify({ type, payload }));
  }

  close(): void {
    this.ws.close();
  }

" <> methods <> "\n}"
}

/// The `import { ... } from client_module` line for the stores file — each
/// subscribed channel's class plus the named types its payloads reference
/// (primitives and arrays need no import).
fn store_imports(spec: AsyncCodegenIR, client_module: String) -> String {
  let names =
    spec.channels
    |> list.flat_map(fn(ch) {
      let class_name = to_pascal(ch.name) <> "Channel"
      // subscribe messages = operations whose (server) action is Send
      let subscribe_payloads =
        ch.operations
        |> list.filter(fn(op) { op.action == ir.Send })
        |> list.flat_map(fn(op) { op.messages })
        |> list.flat_map(fn(msg) { named_types(msg.payload) })

      case ch.operations |> list.any(fn(op) { op.action == ir.Send }) {
        False -> []
        True -> [
          class_name,
          ..list.map(subscribe_payloads, fn(n) { "type " <> n })
        ]
      }
    })
    |> unique
    |> string.join(", ")

  "import { " <> names <> " } from \"" <> client_module <> "\";"
}

/// The named-type names a `TypeRef` references, looking through arrays and
/// nullable/optional wrappers.
fn named_types(ref: nori_ir.TypeRef) -> List(String) {
  case ref {
    nori_ir.Named(name) -> [name]
    nori_ir.Array(item) -> named_types(item)
    nori_ir.Nullable(inner) -> named_types(inner)
    nori_ir.Optional(inner) -> named_types(inner)
    nori_ir.Dict(_, value) -> named_types(value)
    _ -> []
  }
}

fn unique(items: List(String)) -> List(String) {
  items
  |> list.fold([], fn(acc, x) {
    case list.contains(acc, x) {
      True -> acc
      False -> [x, ..acc]
    }
  })
  |> list.reverse
}

// ---------------------------------------------------------------------------
// Payload types
// ---------------------------------------------------------------------------

fn type_def_to_ts(td: nori_ir.TypeDef) -> String {
  case td {
    nori_ir.RecordType(name:, fields:, description:) -> {
      let body =
        fields
        |> list.map(fn(f) {
          let opt = case f.required {
            True -> ""
            False -> "?"
          }
          "  " <> f.name <> opt <> ": " <> type_ref_to_ts(f.type_ref) <> ";"
        })
        |> string.join("\n")
      doc_comment(description)
      <> "export interface "
      <> name
      <> " {\n"
      <> body
      <> "\n}"
    }
    nori_ir.EnumType(name:, variants:, description:) -> {
      let body =
        variants
        |> list.map(fn(v) { "  | \"" <> v.value <> "\"" })
        |> string.join("\n")
      doc_comment(description)
      <> "export type "
      <> name
      <> " =\n"
      <> body
      <> ";"
    }
    nori_ir.UnionType(name:, members:, description:, ..) -> {
      let body = members |> list.map(type_ref_to_ts) |> string.join(" | ")
      doc_comment(description) <> "export type " <> name <> " = " <> body <> ";"
    }
    nori_ir.AliasType(name:, target:, description:) ->
      doc_comment(description)
      <> "export type "
      <> name
      <> " = "
      <> type_ref_to_ts(target)
      <> ";"
  }
}

fn type_ref_to_ts(ref: nori_ir.TypeRef) -> String {
  case ref {
    nori_ir.Named(name) -> name
    nori_ir.Primitive(p) -> primitive_to_ts(p)
    nori_ir.Array(item) -> type_ref_to_ts(item) <> "[]"
    nori_ir.Dict(_, value) -> "Record<string, " <> type_ref_to_ts(value) <> ">"
    nori_ir.Nullable(inner) -> type_ref_to_ts(inner) <> " | null"
    nori_ir.Optional(inner) -> type_ref_to_ts(inner) <> " | undefined"
    nori_ir.Literal(value) -> "\"" <> value <> "\""
    nori_ir.Unknown -> "unknown"
  }
}

fn primitive_to_ts(p: nori_ir.PrimitiveType) -> String {
  case p {
    nori_ir.PString -> "string"
    nori_ir.PInt -> "number"
    nori_ir.PFloat -> "number"
    nori_ir.PBool -> "boolean"
    nori_ir.PDateTime -> "string"
    nori_ir.PDate -> "string"
    nori_ir.PBinary -> "Blob"
    nori_ir.PUnit -> "null"
  }
}

// ---------------------------------------------------------------------------
// Transport runtime
// ---------------------------------------------------------------------------

type Transport {
  WebSocketTransport
  EventSourceTransport
}

fn default_transport(spec: AsyncCodegenIR) -> Transport {
  case list.first(spec.servers) {
    Ok(s) ->
      case s.protocol {
        ir.Sse | ir.Http | ir.Https -> EventSourceTransport
        _ -> WebSocketTransport
      }
    Error(_) -> WebSocketTransport
  }
}

fn transport_class(t: Transport) -> String {
  case t {
    WebSocketTransport -> "WebSocketTransport"
    EventSourceTransport -> "EventSourceTransport"
  }
}

/// The runtime emitted once per module: a `Transport` interface plus both
/// implementations. `subscribe` returns an unsubscribe function; SSE cannot
/// publish, so its `send` throws.
fn transport_runtime() -> String {
  "export interface Transport {
  send(data: string): void;
  subscribe(handler: (data: string) => void): () => void;
  close(): void;
}

export class WebSocketTransport implements Transport {
  private ws: WebSocket;
  constructor(url: string) {
    this.ws = new WebSocket(url);
  }
  send(data: string): void {
    this.ws.send(data);
  }
  subscribe(handler: (data: string) => void): () => void {
    const listener = (e: MessageEvent) => handler(e.data);
    this.ws.addEventListener(\"message\", listener);
    return () => this.ws.removeEventListener(\"message\", listener);
  }
  close(): void {
    this.ws.close();
  }
}

export class EventSourceTransport implements Transport {
  private es: EventSource;
  constructor(url: string) {
    this.es = new EventSource(url);
  }
  send(_data: string): void {
    throw new Error(\"SSE channels are receive-only and cannot send\");
  }
  subscribe(handler: (data: string) => void): () => void {
    const listener = (e: MessageEvent) => handler(e.data);
    this.es.addEventListener(\"message\", listener);
    return () => this.es.removeEventListener(\"message\", listener);
  }
  close(): void {
    this.es.close();
  }
}

/** Parse a `{ type, payload }` envelope frame. Returns undefined on malformed
 * JSON — logged, not thrown, so one bad frame does not tear down the stream. */
function parseFrame(data: string): { type?: string; payload?: unknown } | undefined {
  try {
    return JSON.parse(data);
  } catch {
    console.warn(\"[asyncapi] dropping unparseable frame:\", data);
    return undefined;
  }
}"
}

// ---------------------------------------------------------------------------
// Channels
// ---------------------------------------------------------------------------

/// A method to emit on a channel class — resolved to the client's perspective.
type Method {
  /// client receives (server `send`): `on<Msg>(handler): () => void`.
  /// `wire_type` is the message name the server stamps into the envelope's
  /// `type` field, used to demux frames on a multi-message channel.
  Subscribe(method: String, wire_type: String, payload: String)
  /// client publishes (server `receive`): `send<Msg>(msg): void`
  Publish(method: String, payload: String)
}

fn channel_to_ts(ch: ChannelIR, default: Transport) -> String {
  let class_name = to_pascal(ch.name) <> "Channel"
  let params = ch.parameters

  let methods =
    ch.operations
    |> list.flat_map(operation_methods)
    |> dedupe_methods
    |> list.map(render_method)
    |> string.join("\n\n")

  doc_comment_str("Channel address: " <> ch.address)
  <> "export class "
  <> class_name
  <> " {\n"
  <> "  private constructor(private readonly transport: Transport) {}\n\n"
  <> connect_static(class_name, ch.address, params, default)
  <> "\n\n"
  <> methods
  <> case methods {
    "" -> ""
    _ -> "\n\n"
  }
  <> "  close(): void {\n    this.transport.close();\n  }\n"
  <> "}"
}

/// Store factories for a channel's subscribe (`on*`) messages. Each returns an
/// object shaped for React's `useSyncExternalStore` — a `subscribe(onChange)`
/// that returns an unsubscribe, and a `getSnapshot()` returning the latest
/// message (referentially stable until a new one arrives). Made a module
/// singleton, it needs no `useEffect`/`useMemo` in components.
fn channel_stores(ch: ChannelIR) -> List(String) {
  let class_name = to_pascal(ch.name) <> "Channel"
  let has_params = case ch.parameters {
    [] -> False
    _ -> True
  }
  let params_type =
    ch.parameters
    |> list.map(fn(p) { p.name <> ": string" })
    |> string.join("; ")

  ch.operations
  |> list.flat_map(operation_methods)
  |> dedupe_methods
  |> list.filter_map(fn(m) {
    case m {
      Subscribe(method:, payload:, ..) ->
        Ok(store_factory(class_name, method, payload, has_params, params_type))
      Publish(..) -> Error(Nil)
    }
  })
}

fn store_factory(
  class_name: String,
  method: String,
  payload: String,
  has_params: Bool,
  params_type: String,
) -> String {
  // strip the leading "on" for the factory name: onCountUpdate → CountUpdate
  let msg_name = string.drop_start(method, 2)
  let #(sig, connect_call) = case has_params {
    True -> #(
      "baseUrl: string, params: { " <> params_type <> " }",
      class_name <> ".connect(baseUrl, params)",
    )
    False -> #("baseUrl: string", class_name <> ".connect(baseUrl)")
  }
  "export function create"
  <> msg_name
  <> "Store("
  <> sig
  <> ") {\n"
  <> "  const channel = "
  <> connect_call
  <> ";\n"
  <> "  let snapshot: "
  <> payload
  <> " | undefined = undefined;\n"
  <> "  const listeners = new Set<() => void>();\n"
  <> "  const stop = channel."
  <> method
  <> "((msg) => {\n"
  <> "    snapshot = msg;\n"
  <> "    listeners.forEach((l) => l());\n"
  <> "  });\n"
  <> "  return {\n"
  <> "    subscribe(onChange: () => void): () => void {\n"
  <> "      listeners.add(onChange);\n"
  <> "      return () => {\n"
  <> "        listeners.delete(onChange);\n"
  <> "      };\n"
  <> "    },\n"
  <> "    getSnapshot(): "
  <> payload
  <> " | undefined {\n"
  <> "      return snapshot;\n"
  <> "    },\n"
  <> "    close(): void {\n"
  <> "      stop();\n"
  <> "      channel.close();\n"
  <> "    },\n"
  <> "  };\n"
  <> "}"
}

/// The `connect` factory — builds the interpolated URL and picks the transport.
fn connect_static(
  class_name: String,
  address: String,
  params: List(ir.ChannelParam),
  default: Transport,
) -> String {
  let transport = transport_class(default)
  case params {
    [] ->
      "  static connect(baseUrl: string): "
      <> class_name
      <> " {\n"
      <> "    return new "
      <> class_name
      <> "(new "
      <> transport
      <> "(`${baseUrl}/"
      <> interpolate(address)
      <> "`));\n"
      <> "  }"
    _ -> {
      let params_type =
        params
        |> list.map(fn(p) { p.name <> ": string" })
        |> string.join("; ")
      "  static connect(baseUrl: string, params: { "
      <> params_type
      <> " }): "
      <> class_name
      <> " {\n"
      <> "    return new "
      <> class_name
      <> "(new "
      <> transport
      <> "(`${baseUrl}/"
      <> interpolate(address)
      <> "`));\n"
      <> "  }"
    }
  }
}

/// Turn an AsyncAPI address (`lobby/{lobbyId}/chat`) into a TS template-literal
/// body (`lobby/${params.lobbyId}/chat`).
fn interpolate(address: String) -> String {
  address
  |> string.replace("{", "${params.")
  |> string.replace("}", "}")
}

/// One operation contributes one method per message, its direction flipped to
/// the client's perspective.
fn operation_methods(op: OperationIR) -> List(Method) {
  list.map(op.messages, fn(msg) { message_method(op, msg) })
}

fn message_method(op: OperationIR, msg: MessageIR) -> Method {
  let payload = type_ref_to_ts(msg.payload)
  let msg_name = to_pascal(msg.name)
  case op.action {
    // server sends → client subscribes
    ir.Send -> Subscribe("on" <> msg_name, msg.name, payload)
    // server receives → client publishes
    ir.Receive -> Publish("send" <> msg_name, payload)
  }
}

fn render_method(m: Method) -> String {
  case m {
    Subscribe(method:, wire_type:, payload:) ->
      "  /** Subscribe to `"
      <> payload
      <> "` messages. Returns an unsubscribe function. */\n"
      <> "  "
      <> method
      <> "(handler: (msg: "
      <> payload
      <> ") => void): () => void {\n"
      <> "    return this.transport.subscribe((data) => {\n"
      <> "      const env = parseFrame(data);\n"
      <> "      if (env?.type === \""
      <> wire_type
      <> "\") handler(env.payload as "
      <> payload
      <> ");\n"
      <> "    });\n"
      <> "  }"
    Publish(method:, payload:) ->
      "  /** Publish a `"
      <> payload
      <> "` message. */\n"
      <> "  "
      <> method
      <> "(msg: "
      <> payload
      <> "): void {\n"
      <> "    this.transport.send(JSON.stringify(msg));\n"
      <> "  }"
  }
}

fn dedupe_methods(methods: List(Method)) -> List(Method) {
  methods
  |> list.fold(#([], []), fn(acc, m) {
    let #(seen, out) = acc
    let name = method_name(m)
    case list.contains(seen, name) {
      True -> acc
      False -> #([name, ..seen], [m, ..out])
    }
  })
  |> fn(acc) { list.reverse(acc.1) }
}

fn method_name(m: Method) -> String {
  case m {
    Subscribe(method:, ..) -> method
    Publish(method:, ..) -> method
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn doc_comment(desc: Option(String)) -> String {
  case desc {
    Some(d) -> doc_comment_str(d)
    None -> ""
  }
}

fn doc_comment_str(d: String) -> String {
  "/** " <> d <> " */\n"
}

fn to_pascal(name: String) -> String {
  name
  |> string.replace("/", "_")
  |> string.replace("{", "")
  |> string.replace("}", "")
  |> string.split("_")
  |> list.map(capitalize)
  |> string.join("")
}

fn capitalize(s: String) -> String {
  case string.pop_grapheme(s) {
    Ok(#(head, tail)) -> string.uppercase(head) <> tail
    Error(_) -> s
  }
}
